apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: agro-medicoes
  labels:
    app: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1025 #SMTP
            - containerPort: 8025 #UI
          env:
            - name: MP_SMTP_BIND_ADDR
              value: "0.0.0.0:1025"
            - name: MP_UI_BIND_ADDR
              value: "0.0.0.0:8025"