apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: agro-medicoes
spec:
  type: NodePort
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
      nodePort: 31025
    - name: ui
      port: 8025
      targetPort: 8025
      nodePort: 30025