apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: agro-medicoes
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: docker-compose
        environment: development

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: otel-collector
        honor_labels: true
        static_configs:
          - targets: ['otel-collector:8888']

      - job_name: worker-medicoes
        honor_labels: true
        static_configs:
          - targets: ['otel-collector:8889']

      - job_name: tempo
        static_configs:
          - targets: ['tempo:3200']

      - job_name: loki
        static_configs:
          - targets: ['loki:3100']

